### ISSUE TITLE
Fireplace works nested in X but not alone

### ISSUE THREAD

**Issue by IntrepidPig** [Drakulix/fireplace#21]
I can run and use fireplace just fine running it nested in X, but if I try to start it by itself, then I get this error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:860
stack backtrace:
   1:     0x55f48c6cae2a - std::sys::imp::backtrace::tracing::imp::write::h55f5b644254d8997
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55f48c6ca2b1 - std::panicking::default_hook::{{closure}}::h5341ac454af9dec5
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x55f48c6c9417 - std::panicking::rust_panic_with_hook::h0c50036d8a952120
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:545
   4:     0x55f48c6c8f71 - std::panicking::begin_panic::h549a5cdf22ed84a1
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:507
   5:     0x55f48c6c8ee9 - std::panicking::begin_panic_fmt::h1e2376a100034ec9
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:491
   6:     0x55f48c6d9ec6 - core::panicking::panic_fmt::hfaaf47fca562bd04
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:467
   7:     0x55f48c574934 - core::result::unwrap_failed::hecb9163d22f60696
   8:     0x55f48c58d443 - fireplace::main::he139e971b4d1bd57
   9:     0x55f48c5951e1 - main
  10:     0x7f9580b3c290 - __libc_start_main
  11:     0x55f48c4d5b09 - _start
  12:                0x0 - <unknown>
```
I'm using a default fireplace.yaml in my ~/.config dir. I'm starting it by going to lightdm, switching the session to fireplace, and also starting it from a tty.

**Comment by Drakulix** [comment]
From the backtrace I get, that fireplace most likely does not find it's config file or a file linked in your config file. Because you said you are using the default config the latter is not possible, but it could be that your environment is different in X, than in the tty, especially `XDG_CONFIG_DIR` is important here.

If you get no new information from that, could you do a debug build (no `--release`) and give me another b acktrace? Then I'd get some line information.

**Comment by IntrepidPig** [comment]
Hey I'm sorry but I had two issues going on here. That error was caused by the log file in issue #22. I can run fireplace nested in X, and I can start it from a tty now, but I can't start it from LightDM. The log file only has `Feb 16 09:47:44.927 ERRO "Not running from X11 and no access to /dev/input/event0 or logind unavailable", Library: WLC, version: 1.0.2`

**Comment by Drakulix** [comment]
Yes, that is expected. If you do not use systemd-logind or a display manager you need to set the suid bit on the fireplace executable to make it start as `root`. It will drop privileges, but otherwise it will not be able to open the hardware devices.

**Comment by Drakulix** [comment]
Leaving this up, because it should be better documented.
