### ISSUE TITLE
If configured to use a log file, the directory ~/.local/share/fireplace must be created manually

### ISSUE THREAD

**Issue by IntrepidPig** [Drakulix/fireplace#22]
If you don't create it, you get an error ``thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:860``

**Comment by Drakulix** [comment]
Is this a better description of #21 ?
Definitely something that should be fixed, thanks for reporting

**Comment by Drakulix** [comment]
@IntrepidPig Do you think I should rather provide a better example in the default config and provide a nicer error message, you would you actually prefer the folder to be created by fireplace?
I am in two minds, if it should do that.

**Comment by theduke** [comment]
Just create it. I don't see a downside.

**Comment by Drakulix** [comment]
Fixed by #23. Thanks @IntrepidPig  !!
