### ISSUE TITLE
scaling doesn't work properly

### ISSUE THREAD

**Issue by dbrodie** [Drakulix/fireplace#35]
It seems that when scale is set to 2, the actual windows size isn't scaled properly. For example, a full screen window is twice the size of the screen. Also the positioning seems wrong.

Attached a screenshot showing the problem.
![screenshot from 2017-02-27 12-01-31](https://cloud.githubusercontent.com/assets/98273/23357013/b3073122-fce4-11e6-8019-ab4635264698.png)

**Comment by Drakulix** [comment]
Working on it.

**Comment by Drakulix** [comment]
Should be fixed in version 3.1.1.
Please reopen, if you still experience issues.

**Comment by dbrodie** [comment]
Works amazing now, thanks!
